/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Ecosystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shreya
 */
public class AddDataUI extends javax.swing.JPanel {

    /**
     * Creates new form AddDataUI
     */
    Ecosystem ecosystem;
    JPanel workArea;
    public AddDataUI(JPanel workArea,Ecosystem ecosystem) {
        initComponents();
        this.ecosystem = ecosystem;
        this.workArea = workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddPatient = new javax.swing.JButton();
        btnAddCity = new javax.swing.JButton();
        btnAddPharmacyAdmin = new javax.swing.JButton();
        btnAddDoctor = new javax.swing.JButton();
        btnAddHospitalAdmin = new javax.swing.JButton();
        btnAddTreatmentUnitAdmin = new javax.swing.JButton();
        btnAddNGOAdmin = new javax.swing.JButton();
        btnAddInsuranceAdmin = new javax.swing.JButton();
        btnAddLabAdmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adding Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        btnAddPatient.setBackground(new java.awt.Color(0, 0, 0));
        btnAddPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPatient.setText("Add Patient");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });
        add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 173, -1));

        btnAddCity.setBackground(new java.awt.Color(0, 0, 0));
        btnAddCity.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCity.setText("Add City");
        btnAddCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCityActionPerformed(evt);
            }
        });
        add(btnAddCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 173, -1));

        btnAddPharmacyAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnAddPharmacyAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPharmacyAdmin.setText("Add Pharmacy Admin");
        btnAddPharmacyAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPharmacyAdminActionPerformed(evt);
            }
        });
        add(btnAddPharmacyAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 173, -1));

        btnAddDoctor.setBackground(new java.awt.Color(0, 0, 0));
        btnAddDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDoctor.setText("Add Doctor");
        btnAddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDoctorActionPerformed(evt);
            }
        });
        add(btnAddDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 173, -1));

        btnAddHospitalAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnAddHospitalAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddHospitalAdmin.setText("Add Hospital admin");
        btnAddHospitalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalAdminActionPerformed(evt);
            }
        });
        add(btnAddHospitalAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 173, -1));

        btnAddTreatmentUnitAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnAddTreatmentUnitAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTreatmentUnitAdmin.setText("Add Treatment Unit Admin");
        btnAddTreatmentUnitAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTreatmentUnitAdminActionPerformed(evt);
            }
        });
        add(btnAddTreatmentUnitAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        btnAddNGOAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnAddNGOAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNGOAdmin.setText("Add NGO Admin");
        btnAddNGOAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNGOAdminActionPerformed(evt);
            }
        });
        add(btnAddNGOAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 173, -1));

        btnAddInsuranceAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnAddInsuranceAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddInsuranceAdmin.setText("Add Insurance Admin");
        btnAddInsuranceAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInsuranceAdminActionPerformed(evt);
            }
        });
        add(btnAddInsuranceAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 173, -1));

        btnAddLabAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnAddLabAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLabAdmin.setText("Add Lab Admin");
        btnAddLabAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLabAdminActionPerformed(evt);
            }
        });
        add(btnAddLabAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 173, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/bg1.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
//                AddDataUI AdminLanding = new AddDataUI(WorkArea,ecosystem);
                if(!ecosystem.getCityList().getCityList().isEmpty()){
                AddPatientJPanelUI addPatientJPanelUI = new AddPatientJPanelUI(workArea,ecosystem);
                workArea.add("System Admin",addPatientJPanelUI);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Please add city before proceeding");
                }
    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void btnAddCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCityActionPerformed
                AddCityJPanelUI addCityJPanelUI = new AddCityJPanelUI(workArea,ecosystem);
                workArea.add("System Admin",addCityJPanelUI);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCityActionPerformed

    private void btnAddPharmacyAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPharmacyAdminActionPerformed
        // TODO add your handling code here:
        if(!ecosystem.getCityList().getCityList().isEmpty() && !ecosystem.getHospitalList().getHospitalList().isEmpty()){
            AddPharmacyAdminJPanelUI addPharmacyAdminJPanelUI = new AddPharmacyAdminJPanelUI(workArea,ecosystem);
                workArea.add("System Admin",addPharmacyAdminJPanelUI);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
        }
        else{
                    JOptionPane.showMessageDialog(this,"Please add city and hospitals before proceeding");
            }
    }//GEN-LAST:event_btnAddPharmacyAdminActionPerformed

    private void btnAddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDoctorActionPerformed
        // TODO add your handling code here:
        if(!ecosystem.getCityList().getCityList().isEmpty() && !ecosystem.getHospitalList().getHospitalList().isEmpty()){
        AddDoctorJPanelUI addDoctorJPanelUI = new AddDoctorJPanelUI(workArea,ecosystem);
                workArea.add("System Admin",addDoctorJPanelUI);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
        }
                else{
                    JOptionPane.showMessageDialog(this,"Please add city and hospitals before proceeding");
            }
    }//GEN-LAST:event_btnAddDoctorActionPerformed

    private void btnAddHospitalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalAdminActionPerformed
        // TODO add your handling code here:
        if(!ecosystem.getCityList().getCityList().isEmpty()){
                 AddHospitalAdminJPanelUI addHospitalAdminJPanelUI = new AddHospitalAdminJPanelUI(workArea,ecosystem);
                workArea.add("System Admin",addHospitalAdminJPanelUI);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
        }
        else{
            JOptionPane.showMessageDialog(this,"Please add city before proceeding");
        }
    }//GEN-LAST:event_btnAddHospitalAdminActionPerformed

    private void btnAddTreatmentUnitAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTreatmentUnitAdminActionPerformed
        // TODO add your handling code here:
        if(!ecosystem.getCityList().getCityList().isEmpty() && !ecosystem.getHospitalList().getHospitalList().isEmpty()){
                AddTreatmentUnitAdminJPanelUI addTreatmentUnitAdminJPanelUI = new AddTreatmentUnitAdminJPanelUI(workArea,ecosystem);
                workArea.add("System Admin",addTreatmentUnitAdminJPanelUI);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Please add city and hospitals before proceeding");
            }
    }//GEN-LAST:event_btnAddTreatmentUnitAdminActionPerformed

    private void btnAddNGOAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNGOAdminActionPerformed
        // TODO add your handling code here:
        if(!ecosystem.getCityList().getCityList().isEmpty()){
        AddNGOAdminJPanelUI AddNGOAdminJPanelUI = new AddNGOAdminJPanelUI(workArea,ecosystem);
                workArea.add("System Admin",AddNGOAdminJPanelUI);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
        }
        else{
            JOptionPane.showMessageDialog(this,"Please add city before proceeding");
        }
    }//GEN-LAST:event_btnAddNGOAdminActionPerformed

    private void btnAddInsuranceAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInsuranceAdminActionPerformed
        // TODO add your handling code here:
        
        AddInsuranceAdminJPanelUI AddInsuranceAdminJPanelUI = new AddInsuranceAdminJPanelUI(workArea,ecosystem);
                workArea.add("System Admin",AddInsuranceAdminJPanelUI);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
    }//GEN-LAST:event_btnAddInsuranceAdminActionPerformed

    private void btnAddLabAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLabAdminActionPerformed
        // TODO add your handling code here:
        if(!ecosystem.getCityList().getCityList().isEmpty() && !ecosystem.getHospitalList().getHospitalList().isEmpty()){
        AddLabAdminJPanelUI AddLabAdminJPanelUI = new AddLabAdminJPanelUI(workArea,ecosystem);
                workArea.add("System Admin",AddLabAdminJPanelUI);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
        }else{
            JOptionPane.showMessageDialog(this,"Please add city and hospitals before proceeding");
        }
    }//GEN-LAST:event_btnAddLabAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCity;
    private javax.swing.JButton btnAddDoctor;
    private javax.swing.JButton btnAddHospitalAdmin;
    private javax.swing.JButton btnAddInsuranceAdmin;
    private javax.swing.JButton btnAddLabAdmin;
    private javax.swing.JButton btnAddNGOAdmin;
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnAddPharmacyAdmin;
    private javax.swing.JButton btnAddTreatmentUnitAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
