/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Ecosystem;
import Business.Model.City;
import Business.Model.Hospital;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shreya
 */
public class AddHospitalAdminJPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form AddHospitalAdminJPanelUI
     */
    Ecosystem ecosystem;
        JPanel workArea;
    
    public AddHospitalAdminJPanelUI(JPanel workArea,Ecosystem e) {
        initComponents();
        this.ecosystem = e;
        this.workArea = workArea;
        populateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtHospitalAdminCIty = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtHospitalAdminLocation = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtHospitalAdminName = new javax.swing.JTextField();
        txtHospitalAdminPassword = new javax.swing.JTextField();
        txtHospitalAdminUsername = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("City:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 327, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 432, 111, 43));

        txtHospitalAdminCIty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalAdminCItyActionPerformed(evt);
            }
        });
        add(txtHospitalAdminCIty, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 327, 177, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Password:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 278, -1, -1));
        add(txtHospitalAdminLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 367, 177, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Location:");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 373, -1, -1));
        add(txtHospitalAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 191, 177, -1));
        add(txtHospitalAdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 275, 177, -1));
        add(txtHospitalAdminUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 235, 177, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Hospital Name:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 194, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Username:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 238, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Hospital Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/bg2 small.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 800, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String name = txtHospitalAdminName.getText();
        String username = txtHospitalAdminUsername.getText();
        String password = txtHospitalAdminPassword.getText();
        String city = txtHospitalAdminCIty.getSelectedItem().toString();
        String location = txtHospitalAdminLocation.getText();

        if(name.isEmpty() || username.isEmpty() || password.isEmpty() || city.isEmpty() || location.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter all mandatory fields");

        }

        else {

            for(Hospital h : ecosystem.getHospitalList().getHospitalList())
            {
                if((h.getUsername().equalsIgnoreCase(username))&& (h.getPassword().equalsIgnoreCase(password)))
                {

                    JOptionPane.showMessageDialog(this, "HOspital Admin's Username and password should be unique");
                    return;

                }
            }

            City c = ecosystem.getCityList().findCityByCityName(city);

            Hospital h = ecosystem.getHospitalList().addHospital();
            h.setHospitalName(name);
            h.setUsername(username);
            h.setPassword(password);
            h.setCity(c);
            h.setLocation(location);

            JOptionPane.showMessageDialog(this, "Hospital and Hospital Admin Created");

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtHospitalAdminCItyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalAdminCItyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalAdminCItyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
CardLayout cardLayout = (CardLayout) workArea.getLayout();
        workArea.remove(this);
        cardLayout.previous(workArea);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JComboBox<String> txtHospitalAdminCIty;
    private javax.swing.JTextField txtHospitalAdminLocation;
    private javax.swing.JTextField txtHospitalAdminName;
    private javax.swing.JTextField txtHospitalAdminPassword;
    private javax.swing.JTextField txtHospitalAdminUsername;
    // End of variables declaration//GEN-END:variables

    private void populateCombo() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        if(!ecosystem.getCityList().getCityList().isEmpty()){
            for(City c: ecosystem.getCityList().getCityList()){
                txtHospitalAdminCIty.addItem(c.getCityName());
            }
        }
    
    }
}
