/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Ecosystem;
import Business.Model.InsuranceAdmin;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shreya
 */
public class AddInsuranceAdminJPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form AddInsuranceAdminJPanelUI
     */
    Ecosystem ecosystem;
        JPanel workArea;
    
    public AddInsuranceAdminJPanelUI(JPanel workArea,Ecosystem e) {
        initComponents();
        this.ecosystem = e;
        this.workArea = workArea;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtInsuranceAdminPremium = new javax.swing.JTextField();
        txtInsuranceAdminCoverage = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txtInsuranceAdminName = new javax.swing.JTextField();
        txtInsuranceAdminUsername = new javax.swing.JTextField();
        txtInsuranceAdminPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Inusrance Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 32, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        add(txtInsuranceAdminPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 240, 204, -1));

        txtInsuranceAdminCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuranceAdminCoverageActionPerformed(evt);
            }
        });
        add(txtInsuranceAdminCoverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 268, 204, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Name :");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 159, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("Username:");
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 187, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setText("Coverage:");
        add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 271, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setText("Premium:");
        add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 243, -1, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setText("Password:");
        add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 215, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Add Insurance");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 149, 38));
        add(txtInsuranceAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 156, 204, -1));
        add(txtInsuranceAdminUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 184, 204, -1));
        add(txtInsuranceAdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 212, 204, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/bg2 small.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 800, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void txtInsuranceAdminCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuranceAdminCoverageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsuranceAdminCoverageActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String name = txtInsuranceAdminName.getText();
        String username = txtInsuranceAdminUsername.getText();
        String password = txtInsuranceAdminPassword.getText();
        int premium = Integer.parseInt(txtInsuranceAdminPremium.getText());
        int coverage = Integer.parseInt(txtInsuranceAdminCoverage.getText());

        if(name.isEmpty() || username.isEmpty() || password.isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Enter all mandatory fields");
        }

        else
        {

            for(InsuranceAdmin  ia : ecosystem.getInsuranceAdminList().getInsuranceAdminList())
            {
                if((ia.getUsername().equalsIgnoreCase(username))&& (ia.getPassword().equalsIgnoreCase(password)))
                {

                    JOptionPane.showMessageDialog(this, "Insurance Admin's Username and password should be unique");
                    return;

                }
            }

            InsuranceAdmin ia = ecosystem.getInsuranceAdminList().addInsuranceAdmin();

            ia.setName(name);;
            ia.setUsername(username);
            ia.setPassword(password);
            ia.setPremium(premium);
            ia.setCoverage(coverage);

            JOptionPane.showMessageDialog(this, "Insurance and Admin is Added");

        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
CardLayout cardLayout = (CardLayout) workArea.getLayout();
        workArea.remove(this);
        cardLayout.previous(workArea);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JTextField txtInsuranceAdminCoverage;
    private javax.swing.JTextField txtInsuranceAdminName;
    private javax.swing.JTextField txtInsuranceAdminPassword;
    private javax.swing.JTextField txtInsuranceAdminPremium;
    private javax.swing.JTextField txtInsuranceAdminUsername;
    // End of variables declaration//GEN-END:variables
}
