/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Admins.NGOAdmin;
import Business.Ecosystem;
import Business.Model.City;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shreya
 */
public class AddNGOAdminJPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form AddNGOAdminJPanelUI
     */
  Ecosystem ecosystem;
        JPanel workArea;
    
    public AddNGOAdminJPanelUI(JPanel workArea,Ecosystem e) {
        initComponents();
        this.ecosystem = e;
        this.workArea = workArea;
        populateCombo();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNGOAdminPassword = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtNGOAdminCity = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtNGOAdminName = new javax.swing.JTextField();
        txtNGOAdminUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNGOAdminPassword1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtNGOAdminCity1 = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtNGOAdminName1 = new javax.swing.JTextField();
        txtNGOAdminUsername1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        txtNGOAdminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNGOAdminPasswordActionPerformed(evt);
            }
        });

        jLabel36.setText("Name:");

        jLabel37.setText("Username:");

        jLabel38.setText("Password:");

        txtNGOAdminCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel39.setText("City");

        jButton3.setText("Add NGO/ NGO Admin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtNGOAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNGOAdminNameActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add NGO Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 24, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 8, -1, -1));

        txtNGOAdminPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNGOAdminPassword1ActionPerformed(evt);
            }
        });
        add(txtNGOAdminPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 244, 193, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Name:");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 179, 60, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Username:");
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 213, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Password:");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 250, 60, -1));

        add(txtNGOAdminCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 284, 193, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("City :");
        add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 287, 60, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add NGO Admin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 346, 138, 35));

        txtNGOAdminName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNGOAdminName1ActionPerformed(evt);
            }
        });
        add(txtNGOAdminName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 176, 193, -1));
        add(txtNGOAdminUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 210, 193, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/bg2 small.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 800, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
CardLayout cardLayout = (CardLayout) workArea.getLayout();
        workArea.remove(this);
        cardLayout.previous(workArea);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNGOAdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNGOAdminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOAdminPasswordActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String name = txtNGOAdminName.getText();
        String username = txtNGOAdminUsername.getText();
        String password = txtNGOAdminPassword.getText();
        String city = txtNGOAdminCity.getSelectedItem().toString();

        if(name.isEmpty() || username.isEmpty() || password.isEmpty() || city.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter all mandatory fields");

        }

        else
        {

            for(NGOAdmin  na : ecosystem.getnGOAdminList().getNgoAdminList())
            {
                if((na.getUsername().equalsIgnoreCase(username))&& (na.getPassword().equalsIgnoreCase(password)))
                {

                    JOptionPane.showMessageDialog(this, "NGO admin's Username and password should be unique");
                    return;

                }
            }

            City c = ecosystem.getCityList().findCityByCityName(city);

            NGOAdmin ngoAdmin = ecosystem.getnGOAdminList().addNGOAdmin();
            ngoAdmin.setName(name);
            ngoAdmin.setUsername(username);
            ngoAdmin.setPassword(password);
            ngoAdmin.setCity(c);

            JOptionPane.showMessageDialog(this, "NGO and NGO admin created");

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtNGOAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNGOAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOAdminNameActionPerformed

    private void txtNGOAdminPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNGOAdminPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOAdminPassword1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = txtNGOAdminName1.getText();
        String username = txtNGOAdminUsername1.getText();
        String password = txtNGOAdminPassword1.getText();
        String city = txtNGOAdminCity1.getSelectedItem().toString();

        if(name.isEmpty() || username.isEmpty() || password.isEmpty() || city.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter all mandatory fields");

        }

        else
        {

            for(NGOAdmin  na : ecosystem.getnGOAdminList().getNgoAdminList())
            {
                if((na.getUsername().equalsIgnoreCase(username))&& (na.getPassword().equalsIgnoreCase(password)))
                {
                    JOptionPane.showMessageDialog(this, "NGO admin's Username and password should be unique");
                    return;
                }
            }

            City c = ecosystem.getCityList().findCityByCityName(city);

            NGOAdmin ngoAdmin = ecosystem.getnGOAdminList().addNGOAdmin();
            ngoAdmin.setName(name);
            ngoAdmin.setUsername(username);
            ngoAdmin.setPassword(password);
            ngoAdmin.setCity(c);

            JOptionPane.showMessageDialog(this, "NGO and NGO admin created");

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNGOAdminName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNGOAdminName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOAdminName1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JComboBox<String> txtNGOAdminCity;
    private javax.swing.JComboBox<String> txtNGOAdminCity1;
    private javax.swing.JTextField txtNGOAdminName;
    private javax.swing.JTextField txtNGOAdminName1;
    private javax.swing.JTextField txtNGOAdminPassword;
    private javax.swing.JTextField txtNGOAdminPassword1;
    private javax.swing.JTextField txtNGOAdminUsername;
    private javax.swing.JTextField txtNGOAdminUsername1;
    // End of variables declaration//GEN-END:variables

    private void populateCombo() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        if(!ecosystem.getCityList().getCityList().isEmpty()){
            for(City c: ecosystem.getCityList().getCityList()){
                txtNGOAdminCity1.addItem(c.getCityName());
            }
        }
    
    }
}
