/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Ecosystem;
import Business.Model.City;
import Business.Model.Patient;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shreya
 */
public class AddPatientJPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form AddPatientJPanelUI
     */
    Ecosystem ecosystem;
    JPanel workArea;
    public AddPatientJPanelUI(JPanel workArea,Ecosystem e) {
        initComponents();
        this.ecosystem = e;
        this.workArea = workArea;
        populateCityCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPatientCity = new javax.swing.JComboBox<>();
        txtPatientPurpose = new javax.swing.JTextField();
        btnCreatePatient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        txtPatientUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPatientPassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPatientAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPatientPhone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jdateChooser = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPatientCity.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtPatientCityComponentShown(evt);
            }
        });
        txtPatientCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientCityActionPerformed(evt);
            }
        });
        add(txtPatientCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 136, -1));
        add(txtPatientPurpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 136, -1));

        btnCreatePatient.setBackground(new java.awt.Color(0, 0, 0));
        btnCreatePatient.setForeground(new java.awt.Color(255, 255, 255));
        btnCreatePatient.setText("Create a Patient");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });
        add(btnCreatePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 427, 147, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Purpose:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 82, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 82, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 82, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Address:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 82, -1));
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 136, -1));

        Username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Username.setText("Username:");
        add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 82, -1));
        add(txtPatientUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 136, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Phone number:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 115, -1));
        add(txtPatientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 136, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Date:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 82, -1));

        txtPatientAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientAddressActionPerformed(evt);
            }
        });
        add(txtPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 136, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("City:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 82, -1));
        add(txtPatientPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 136, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Patients");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));
        add(jdateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 140, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/bg2 small.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientCityComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtPatientCityComponentShown

    }//GEN-LAST:event_txtPatientCityComponentShown

    private void txtPatientCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientCityActionPerformed

    }//GEN-LAST:event_txtPatientCityActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed

        String name = txtPatientName.getText();
        String username=txtPatientUsername.getText();
        String password = txtPatientPassword.getText();
        String address = txtPatientAddress.getText();
        String city= txtPatientCity.getSelectedItem().toString();

        Date date = jdateChooser.getDate();
        String purpose = txtPatientPurpose.getText();

        if(name.isEmpty() || username.isEmpty() || password.isEmpty() || address.isEmpty() || city.isEmpty() ||  date.equals("")|| purpose.isEmpty() || txtPatientPhone.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please provide all mandatory fields");

        }

        else{

            for(Patient p : ecosystem.getPatientList().getPatientList())
            {
                if((p.getUsername().equalsIgnoreCase(username))&& (p.getPassword().equalsIgnoreCase(password)))
                {

                    JOptionPane.showMessageDialog(this, "Patient's Username and password should be unique");
                    return;

                }
            }

            City c = ecosystem.getCityList().findCityByCityName(city);

            double phone = Double.parseDouble(txtPatientPhone.getText());

            Patient p = ecosystem.getPatientList().addPatient();
            p.setName(name);
            p.setUsername(username);
            p.setPassword(password);
            p.setPurpose(purpose);
            p.setPhone(phone);
            p.setAddress(address);
            p.setCity(c);
            p.setDate(date);

            JOptionPane.showMessageDialog(this, "Patient is Created");

            txtPatientName.setText("");
            txtPatientUsername.setText("");
            txtPatientPassword.setText("");
            txtPatientPhone.setText("");
            txtPatientPurpose.setText("");
            txtPatientAddress.setText("");
            jdateChooser.setDate(null);

        }

    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void txtPatientAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientAddressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) workArea.getLayout();
        workArea.remove(this);
        cardLayout.previous(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdateChooser;
    private javax.swing.JTextField txtPatientAddress;
    private javax.swing.JComboBox<String> txtPatientCity;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPatientPassword;
    private javax.swing.JTextField txtPatientPhone;
    private javax.swing.JTextField txtPatientPurpose;
    private javax.swing.JTextField txtPatientUsername;
    // End of variables declaration//GEN-END:variables

    private void populateCityCombo() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        if(!ecosystem.getCityList().getCityList().isEmpty()){
            for(City c: ecosystem.getCityList().getCityList()){
                txtPatientCity.addItem(c.getCityName());
            }
        }
    }
}
