/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Admins.PharmacyAdmin;
import Business.Ecosystem;
import Business.Model.City;
import Business.Model.Hospital;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shreya
 */
public class AddPharmacyAdminJPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form AddPharmacyAdminJPanelUI
     */
         Ecosystem ecosystem;
        JPanel workArea;
    
    public AddPharmacyAdminJPanelUI(JPanel workArea,Ecosystem e) {
        initComponents();
        this.ecosystem = e;
        this.workArea = workArea;
        populateCombos();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPharAdminHospital = new javax.swing.JComboBox<>();
        btnSavePharAdmin = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtPharAdminName = new javax.swing.JTextField();
        txtPharAdminUsername = new javax.swing.JTextField();
        txtPharAdminPassword = new javax.swing.JTextField();
        txtPharAdminCity = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(txtPharAdminHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 369, 177, -1));

        btnSavePharAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnSavePharAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnSavePharAdmin.setText("Save");
        btnSavePharAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePharAdminActionPerformed(evt);
            }
        });
        add(btnSavePharAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 150, 36));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Pharmacy Name:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 195, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Username:");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 239, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Password:");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 279, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("City:");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 319, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Hospital:");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 372, -1, -1));
        add(txtPharAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 192, 177, -1));
        add(txtPharAdminUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 236, 177, -1));
        add(txtPharAdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 276, 177, -1));

        txtPharAdminCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPharAdminCityActionPerformed(evt);
            }
        });
        add(txtPharAdminCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 316, 177, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Pharmacy Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/bg2 small.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 870, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePharAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePharAdminActionPerformed

        String pharmAdminName = txtPharAdminName.getText();
        String pharmAdminUsername= txtPharAdminUsername.getText();
        String pharmAdminPassword = txtPharAdminPassword.getText();
        String pharmAdminCity = txtPharAdminCity.getSelectedItem().toString();
        String pharmAdminHospital = txtPharAdminHospital.getSelectedItem().toString();

        if(pharmAdminName.isEmpty() || pharmAdminUsername.isEmpty() || pharmAdminPassword.isEmpty() || pharmAdminCity.isEmpty() || pharmAdminHospital.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please Enter all mandatory fields");

        }

        else{

            for(PharmacyAdmin pa : ecosystem.getPharmacyAdminList().getPharmacyAdminList())
            {
                if((pa.getUsername().equalsIgnoreCase(pharmAdminUsername))&& (pa.getPassword().equalsIgnoreCase(pharmAdminPassword)))
                {

                    JOptionPane.showMessageDialog(this, "Pharmacy Admin's Username and password should be unique");
                    return;

                }
            }

            City c = ecosystem.getCityList().findCityByCityName(pharmAdminCity);
            Hospital h = ecosystem.getHospitalList().findHospitalByHospitalName(pharmAdminHospital);
            h.setHospitalName(pharmAdminHospital);
            System.out.println("here");

            PharmacyAdmin pa = ecosystem.getPharmacyAdminList().addPharmacyAdmin();

            System.out.println("here1");
            pa.setUsername(pharmAdminUsername);
            pa.setName(pharmAdminName);
            pa.setPassword(pharmAdminPassword);
            pa.setCity(c);
            pa.setHospital(h);

            JOptionPane.showMessageDialog(this, "Pharmacy and Pharmacy Admin added");

        }

    }//GEN-LAST:event_btnSavePharAdminActionPerformed

    private void txtPharAdminCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPharAdminCityActionPerformed
        txtPharAdminHospital.removeAllItems();

        for(Hospital h : ecosystem.getHospitalList().getHospitalList() )
        {
            if(h.getCity().getCityName().equals(txtPharAdminCity.getSelectedItem()))
            {
                txtPharAdminHospital.addItem(h.getHospitalName());
            }
        }
    }//GEN-LAST:event_txtPharAdminCityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
CardLayout cardLayout = (CardLayout) workArea.getLayout();
        workArea.remove(this);
        cardLayout.previous(workArea);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSavePharAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JComboBox<String> txtPharAdminCity;
    private javax.swing.JComboBox<String> txtPharAdminHospital;
    private javax.swing.JTextField txtPharAdminName;
    private javax.swing.JTextField txtPharAdminPassword;
    private javax.swing.JTextField txtPharAdminUsername;
    // End of variables declaration//GEN-END:variables

    private void populateCombos() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        if(!ecosystem.getCityList().getCityList().isEmpty()){
            for(City c: ecosystem.getCityList().getCityList()){
                txtPharAdminCity.addItem(c.getCityName());
            }
        }
        if(!ecosystem.getHospitalList().getHospitalList().isEmpty()){
            for(Hospital h : ecosystem.getHospitalList().getHospitalList()){
                txtPharAdminHospital.addItem(h.getHospitalName());
            }
        }
    
    }
}
