/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Admins.TreatmentUnitAdmin;
import Business.Ecosystem;
import Business.Model.City;
import Business.Model.Hospital;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shreya
 */
public class AddTreatmentUnitAdminJPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form AddTreatmentUnitAdminJPanelUI
     */
  Ecosystem ecosystem;
        JPanel workArea;
    
    public AddTreatmentUnitAdminJPanelUI(JPanel workArea,Ecosystem e) {
        initComponents();
        this.ecosystem = e;
        this.workArea = workArea;
        populateCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        txtTreatAdminName = new javax.swing.JTextField();
        txtTreatAdminUsername = new javax.swing.JTextField();
        txtTreatAdminPassword = new javax.swing.JTextField();
        txtTreatAdminCity = new javax.swing.JComboBox<>();
        txtTreatAdminHospital = new javax.swing.JComboBox<>();
        btnSaveTreatAdmin = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Hospital:");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));
        add(txtTreatAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 177, -1));
        add(txtTreatAdminUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 177, -1));
        add(txtTreatAdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 177, -1));

        txtTreatAdminCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTreatAdminCityActionPerformed(evt);
            }
        });
        add(txtTreatAdminCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 177, -1));

        txtTreatAdminHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTreatAdminHospitalActionPerformed(evt);
            }
        });
        add(txtTreatAdminHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 177, -1));

        btnSaveTreatAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveTreatAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveTreatAdmin.setText("Save");
        btnSaveTreatAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTreatAdminActionPerformed(evt);
            }
        });
        add(btnSaveTreatAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 406, 146, 37));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Treatment Unit Name:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 171, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Username:");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 215, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Password:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 255, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("City:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Treatment Unit Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 35, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/bg2 small.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTreatAdminCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTreatAdminCityActionPerformed
        txtTreatAdminHospital.removeAllItems();

        for(Hospital h : ecosystem.getHospitalList().getHospitalList() )
        {
            if(h.getCity().getCityName().equals(txtTreatAdminCity.getSelectedItem()))
            {
                txtTreatAdminHospital.addItem(h.getHospitalName());
            }
        }
    }//GEN-LAST:event_txtTreatAdminCityActionPerformed

    private void txtTreatAdminHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTreatAdminHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTreatAdminHospitalActionPerformed

    private void btnSaveTreatAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTreatAdminActionPerformed

        String name = txtTreatAdminName.getText();
        String username = txtTreatAdminUsername.getText();
        String password = txtTreatAdminPassword.getText();
        String city = txtTreatAdminCity.getSelectedItem().toString();
        String hospital = txtTreatAdminHospital.getSelectedItem().toString();

        if(name.isEmpty() || username.isEmpty() || password.isEmpty() || city.isEmpty() || hospital.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter all mandatory fields");

        }

        else
        {

            for(TreatmentUnitAdmin tu : ecosystem.getTreatmentUnitAdminList().getTreatmentUnitAdminList())
            {
                if((tu.getUsername().equalsIgnoreCase(username))&& (tu.getPassword().equalsIgnoreCase(password)))
                {

                    JOptionPane.showMessageDialog(this, "Treatment Unit Admin's Username and password should be unique");
                    return;

                }
            }

            City c = ecosystem.getCityList().findCityByCityName(city);
            Hospital h = ecosystem.getHospitalList().findHospitalByHospitalName(hospital);
//            h.setHospitalName(hospital);

            TreatmentUnitAdmin tua = ecosystem.getTreatmentUnitAdminList().addTreatmentUnitAdmin();
            tua.setName(name);
            tua.setUsername(username);
            tua.setPassword(password);
            tua.setCity(c);
            tua.setHospital(h);

            JOptionPane.showMessageDialog(this, "Treatment Unit Admin added");

        }

    }//GEN-LAST:event_btnSaveTreatAdminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
CardLayout cardLayout = (CardLayout) workArea.getLayout();
        workArea.remove(this);
        cardLayout.previous(workArea);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveTreatAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JComboBox<String> txtTreatAdminCity;
    private javax.swing.JComboBox<String> txtTreatAdminHospital;
    private javax.swing.JTextField txtTreatAdminName;
    private javax.swing.JTextField txtTreatAdminPassword;
    private javax.swing.JTextField txtTreatAdminUsername;
    // End of variables declaration//GEN-END:variables

    private void populateCombos() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        if(!ecosystem.getCityList().getCityList().isEmpty()){
            for(City c: ecosystem.getCityList().getCityList()){
                txtTreatAdminCity.addItem(c.getCityName());
            }
        }
        if(!ecosystem.getHospitalList().getHospitalList().isEmpty()){
            for(Hospital h : ecosystem.getHospitalList().getHospitalList()){
                txtTreatAdminHospital.addItem(h.getHospitalName());
            }
        }
    }
}
