/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard.Patient;

import Business.Ecosystem;
import Business.Model.City;
import Business.Model.Doctor;
import Business.Model.Hospital;
import Business.Model.Patient;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shreya
 */
public class PatientNearbyJPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form PatientNearbyJPanelUI
     */
    Patient patient;
    Ecosystem ecosystem;
    JPanel workArea;
    public PatientNearbyJPanelUI(JPanel workArea,Ecosystem ecosystem,Patient patient) {
        initComponents();
        this.workArea = workArea;
        this.patient = patient;
        this.ecosystem = ecosystem;
        populateCityCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboCity = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientHospital = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPatientDoctor = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Select City :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 105, 73, -1));

        comboCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCityActionPerformed(evt);
            }
        });
        jPanel1.add(comboCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 102, 198, -1));

        tblPatientHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Hospital Name", "City"
            }
        ));
        jScrollPane1.setViewportView(tblPatientHospital);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 161, 571, 174));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show Doctors");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 353, -1, -1));

        tblPatientDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Doctor Name", "Doctor Qualification"
            }
        ));
        jScrollPane2.setViewportView(tblPatientDoctor);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 435, 585, 166));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Schedule an Appointment with Doctor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 619, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nearby Hospitals and Doctors");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 18, 426, -1));

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/Patient/bg2 small.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 800, 800));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 800, 1140));
    }// </editor-fold>//GEN-END:initComponents

    private void comboCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCityActionPerformed

        populatePatientHospitalTable(comboCity.getSelectedItem().toString());
    }//GEN-LAST:event_comboCityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int selectedRowIndex = tblPatientHospital.getSelectedRow();

        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row to view");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblPatientHospital.getModel();
        Hospital h = (Hospital) model.getValueAt(selectedRowIndex, 0);
        populatePatientDoctorTable(h.getHospitalName());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int selectedRowIndex = tblPatientDoctor.getSelectedRow();

        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row to view");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblPatientDoctor.getModel();
        Doctor d = (Doctor) model.getValueAt(selectedRowIndex, 0);

        d.getDocPatList().add(patient);
        patient.getDoctors().add(d);

        JOptionPane.showMessageDialog(this, "Appointment scheduled");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) workArea.getLayout();
        workArea.remove(this);
        cardLayout.previous(workArea);    
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPatientDoctor;
    private javax.swing.JTable tblPatientHospital;
    // End of variables declaration//GEN-END:variables

    private void populateMedicalHistory() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    
    }

    private void populatePatientDoctorTable(String hospitalName) {
        DefaultTableModel model = (DefaultTableModel) tblPatientDoctor.getModel();
                  
                model.setRowCount(0);
                
                for(Doctor d : ecosystem.getDoctorList().getDoctorList())
                    
                {
                    
                    if(d.getHospital().getHospitalName().equals(hospitalName))
                    {
                        
                        
                    Object[] row = new Object[2];
                    row[0]=d;
                    row[1]=d.getQualification();
                    
                    
                    
                    
                    model.addRow(row);
                    
                    
                }
    
                }
       
       
    }

    private void populatePatientHospitalTable(String city) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                
                DefaultTableModel model = (DefaultTableModel) tblPatientHospital.getModel();
                  
                model.setRowCount(0);
                
                for(Hospital h: ecosystem.getHospitalList().getHospitalList())
                    
                {
                    
                    if(h.getCity().getCityName().equals(city))
                    {   
                    Object[] row = new Object[2];
                    row[0]=h;
                    row[1]=h.getCity().getCityName();
                    model.addRow(row);
                }
                }
    }

    private void populateCityCombo() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        if(!ecosystem.getCityList().getCityList().isEmpty()){
            for(City c: ecosystem.getCityList().getCityList()){
                comboCity.addItem(c.getCityName());
            }
        }
    }
}
