/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard.Patient;

import Business.Model.Doctor;
import Business.Model.Encounter;
import Business.Model.Medicine;
import Business.Model.Patient;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shreya
 */
public class PatientMedicalHistoryJPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form PatientMedicalHistoryJPanelUI
     */
    Patient patient;
    JPanel workArea;
    public PatientMedicalHistoryJPanelUI(Patient p,JPanel workArea) {
        initComponents();
        this.patient = p;
        this.workArea = workArea;
        populateDoctors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMedHisDoc = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMedHisEncounters = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPatMed = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblPatVitalSigns = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblPatCancerInfo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMedHisDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Doctor Name", "Qualification"
            }
        ));
        jScrollPane3.setViewportView(tblMedHisDoc);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 680, 110));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        tblMedHisEncounters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Encounter Name", "Date", "Doctor Name"
            }
        ));
        jScrollPane4.setViewportView(tblMedHisEncounters);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 680, 124));

        tblPatMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine", "Quantity"
            }
        ));
        jScrollPane5.setViewportView(tblPatMed);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 300, 116));

        tblPatVitalSigns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Heart Rate", "Blood Pressure", "Temperature"
            }
        ));
        jScrollPane7.setViewportView(tblPatVitalSigns);

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 290, 116));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        tblPatCancerInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tumor type", "Severity", "Condition", "Diagnosis", "Treatment Method", "Medicine status", "Laboratory Status", "Treatment Status"
            }
        ));
        jScrollPane6.setViewportView(tblPatCancerInfo);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 770, 116));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Medical History");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/Patient/bg2 small.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -70, 840, 920));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int selectedRowIndex = tblMedHisDoc.getSelectedRow();

        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row of doctor table");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblMedHisDoc.getModel();
        Doctor d = (Doctor) model.getValueAt(selectedRowIndex, 0);
        //-----------------------------------------------------------------------------------------------

        DefaultTableModel model2 = (DefaultTableModel) tblMedHisEncounters.getModel();

        model2.setRowCount(0);

        for(Encounter e : patient.getEncounterHistory())
        {
            if(e.getDoctor().getUsername().equals(d.getUsername()))
            {

                Object[] row = new Object[3];
                row[0]=e;
                row[1]=e.getDate();
                row[2]=e.getDoctor().getUsername();

                model2.addRow(row);

            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int selectedRowIndex = tblMedHisEncounters.getSelectedRow();

        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row of Encounter table");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblMedHisEncounters.getModel();
        Encounter e = (Encounter) model.getValueAt(selectedRowIndex, 0);
        //------------------------------------------------------------------------------------------------------------------------------------
        DefaultTableModel model1 = (DefaultTableModel) tblPatVitalSigns.getModel();
        model1.setRowCount(0);

        Object[] row = new Object[3];
        row[0]=e.getVitalSigns().getHeartRate();
        row[1]=e.getVitalSigns().getBloodPressure();
        row[2]=e.getVitalSigns().getTemperature();

        model1.addRow(row);

        //-------------------------------------------------------------------------------------------------------------------------------------------

        DefaultTableModel model2 = (DefaultTableModel) tblPatMed.getModel();
        model2.setRowCount(0);

        for(Medicine m : e.getTreatment().getMedicineList() )
        {

            Object[] row1 = new Object[3];
            row1[0]=m.getMedicine();
            row1[1]=m.getQuantity();

            model2.addRow(row1);

        }

        //----------------------------------------------------------------------------------------------------------------

        DefaultTableModel model3 = (DefaultTableModel) tblPatCancerInfo.getModel();
        model3.setRowCount(0);

        Object[] row2 = new Object[8];
        row2[0]=e.getVitalSigns().getTumorType();
        row2[1]=e.getVitalSigns().getSeverity();
        row2[2]=e.getVitalSigns().getCondition();

        row2[3]=e.getDiagnosis();
        row2[4]=e.getTreatment().getLaboratoryList().get(0).getLabTest();
        row2[5]=e.getTreatment().getMedicineStatus();
        row2[6]=e.getTreatment().getLaboratoryStatus();
        row2[7]=e.getTreatment().getTreatmentStatus();

        model3.addRow(row2);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) workArea.getLayout();
        workArea.remove(this);
        cardLayout.previous(workArea);    
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tblMedHisDoc;
    private javax.swing.JTable tblMedHisEncounters;
    private javax.swing.JTable tblPatCancerInfo;
    private javax.swing.JTable tblPatMed;
    private javax.swing.JTable tblPatVitalSigns;
    // End of variables declaration//GEN-END:variables

    private void populateDoctors() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel model = (DefaultTableModel) tblMedHisDoc.getModel();
        model.setRowCount(0);
        if(!patient.getDoctors().isEmpty()){
            for(Doctor d : patient.getDoctors()){
                Object[] row = new Object[2];
                row[0] = d;
                row[1] = d.getQualification();
                model.addRow(row);
            }
        }
    }
}
