/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard.Patient;

import Business.Ecosystem;
import Business.Model.InsuranceAdmin;
import Business.Model.Patient;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shreya
 */
public class PatientBuyClaimInsuranceJPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form PatientBuyClaimInsuranceJPanelUI
     */
    Patient patient;
    JPanel workArea;
    Ecosystem ecosystem;
    public PatientBuyClaimInsuranceJPanelUI(Patient p,JPanel workArea,Ecosystem ecosystem) {
        initComponents();
        this.patient = p;
        this.workArea = workArea;
        this.ecosystem = ecosystem;
        populateInsuranceTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblPatientInsurance = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPatientEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Buy Insurance");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 150, 30));

        tblPatientInsurance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Insurance Name", "Premium", "Coverage"
            }
        ));
        jScrollPane8.setViewportView(tblPatientInsurance);

        add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 620, 167));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BUY / CLAIM Insurance");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        add(txtPatientEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 260, -1));

        jLabel3.setText("Please enter your Email ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/Patient/bg2 small.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 800, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(txtPatientEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your email address to be ascertained about the status of your claim");
        }
        else{
        int selectedRowIndex =tblPatientInsurance .getSelectedRow();

        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row of Encounter table");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblPatientInsurance.getModel();

        InsuranceAdmin ia = (InsuranceAdmin) model.getValueAt(selectedRowIndex, 0);

        ia.getInsurancePatientList().add(patient);

        patient.setInsuranceRequest("Pending");

        patient.setInsuranceAdmin(ia);
        
        patient.setEmail(txtPatientEmail.getText());
        
        JOptionPane.showMessageDialog(this, "Insurance Request is raised");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cardLayout = (CardLayout) workArea.getLayout();
        workArea.remove(this);
        cardLayout.previous(workArea);            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tblPatientInsurance;
    private javax.swing.JTextField txtPatientEmail;
    // End of variables declaration//GEN-END:variables

    private void populateInsuranceTable() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel model = (DefaultTableModel) tblPatientInsurance.getModel();
                  
         model.setRowCount(0);
         
         
       for(InsuranceAdmin ia : ecosystem.getInsuranceAdminList().getInsuranceAdminList())
       {
           
                    Object[] row = new Object[3];
                    row[0]=ia;
                    row[1]=ia.getPremium();
                    row[2]=ia.getCoverage();
                    
                    model.addRow(row);
           
           
       }
    }
}
