/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard.Patient;

import Business.Ecosystem;
import Business.Model.Patient;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Shreya
 */
public class PatientDashboardUI extends javax.swing.JPanel {

    /**
     * Creates new form PatientDashboardUI
     */
    Patient patient;
    Ecosystem ecosystem;
    JPanel workArea;
    public PatientDashboardUI(Ecosystem e,Patient p,JPanel workArea) {
        initComponents();
//        this.workArea = workArea;
        this.patient = p;
        this.ecosystem = e;
        this.workArea = workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btnPatientNearby1 = new javax.swing.JButton();
        btnMedicalHistory1 = new javax.swing.JButton();
        btnWalletBalance1 = new javax.swing.JButton();
        btnRaiseReq1 = new javax.swing.JButton();
        btnBuyClaimInsurance1 = new javax.swing.JButton();
        workAreaPatient = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));

        jSplitPane1.setDividerLocation(250);

        btnPatientNearby1.setBackground(new java.awt.Color(0, 0, 0));
        btnPatientNearby1.setForeground(new java.awt.Color(255, 255, 255));
        btnPatientNearby1.setText("View nearby Hospitals and Patients");
        btnPatientNearby1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientNearby1ActionPerformed(evt);
            }
        });

        btnMedicalHistory1.setBackground(new java.awt.Color(0, 0, 0));
        btnMedicalHistory1.setForeground(new java.awt.Color(255, 255, 255));
        btnMedicalHistory1.setText("Medical History");
        btnMedicalHistory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicalHistory1ActionPerformed(evt);
            }
        });

        btnWalletBalance1.setBackground(new java.awt.Color(0, 0, 0));
        btnWalletBalance1.setForeground(new java.awt.Color(255, 255, 255));
        btnWalletBalance1.setText("Add Wallet Balance");
        btnWalletBalance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWalletBalance1ActionPerformed(evt);
            }
        });

        btnRaiseReq1.setBackground(new java.awt.Color(0, 0, 0));
        btnRaiseReq1.setForeground(new java.awt.Color(255, 255, 255));
        btnRaiseReq1.setText("Raise request to NGO");
        btnRaiseReq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseReq1ActionPerformed(evt);
            }
        });

        btnBuyClaimInsurance1.setBackground(new java.awt.Color(0, 0, 0));
        btnBuyClaimInsurance1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuyClaimInsurance1.setText("Buy / Claim Insurance");
        btnBuyClaimInsurance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyClaimInsurance1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnMedicalHistory1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnWalletBalance1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnRaiseReq1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnBuyClaimInsurance1)))
                .addGap(46, 46, 46))
            .addComponent(btnPatientNearby1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnPatientNearby1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedicalHistory1)
                .addGap(5, 5, 5)
                .addComponent(btnWalletBalance1)
                .addGap(5, 5, 5)
                .addComponent(btnRaiseReq1)
                .addGap(5, 5, 5)
                .addComponent(btnBuyClaimInsurance1)
                .addContainerGap(578, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        workAreaPatient.setLayout(new java.awt.CardLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/Patient/bg1.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        workAreaPatient.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(workAreaPatient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientNearby1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientNearby1ActionPerformed
        // TODO add your handling code here:
        PatientNearbyJPanelUI patientNearbyJPanelUI = new PatientNearbyJPanelUI(workAreaPatient, ecosystem, patient);
        CardLayout layout = (CardLayout) workAreaPatient.getLayout();
        workAreaPatient.add("Nearby patients",patientNearbyJPanelUI);
        layout.next(workAreaPatient);
    }//GEN-LAST:event_btnPatientNearby1ActionPerformed

    private void btnMedicalHistory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicalHistory1ActionPerformed
        // TODO add your handling code here:
        PatientMedicalHistoryJPanelUI patientMedicalHistoryJPanelUI = new PatientMedicalHistoryJPanelUI(patient,workAreaPatient);
        CardLayout layout = (CardLayout) workAreaPatient.getLayout();
        workAreaPatient.add("Nearby patients",patientMedicalHistoryJPanelUI);
        layout.next(workAreaPatient);
    }//GEN-LAST:event_btnMedicalHistory1ActionPerformed

    private void btnWalletBalance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWalletBalance1ActionPerformed
        // TODO add your handling code here:
        PatientWalletBalanceJPanelUI patientWalletBalanceJPanelUI = new PatientWalletBalanceJPanelUI(patient,workAreaPatient);
        CardLayout layout = (CardLayout) workAreaPatient.getLayout();
        workAreaPatient.add("Nearby patients",patientWalletBalanceJPanelUI);
        layout.next(workAreaPatient);
    }//GEN-LAST:event_btnWalletBalance1ActionPerformed

    private void btnRaiseReq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseReq1ActionPerformed
        // TODO add your handling code here:
        PatientRaiseReqJPanelUI patientRaiseReqJPanelUI = new PatientRaiseReqJPanelUI(patient,workAreaPatient);
        CardLayout layout = (CardLayout) workAreaPatient.getLayout();
        workAreaPatient.add("Nearby patients",patientRaiseReqJPanelUI);
        layout.next(workAreaPatient);
    }//GEN-LAST:event_btnRaiseReq1ActionPerformed

    private void btnBuyClaimInsurance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyClaimInsurance1ActionPerformed
        // TODO add your handling code here:
        PatientBuyClaimInsuranceJPanelUI patientBuyClaimInsuranceJPanelUI = new PatientBuyClaimInsuranceJPanelUI(patient,workAreaPatient,ecosystem);
        CardLayout layout = (CardLayout) workAreaPatient.getLayout();
        workAreaPatient.add("Nearby patients",patientBuyClaimInsuranceJPanelUI);
        layout.next(workAreaPatient);
    }//GEN-LAST:event_btnBuyClaimInsurance1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyClaimInsurance1;
    private javax.swing.JButton btnMedicalHistory1;
    private javax.swing.JButton btnPatientNearby1;
    private javax.swing.JButton btnRaiseReq1;
    private javax.swing.JButton btnWalletBalance1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workAreaPatient;
    // End of variables declaration//GEN-END:variables
}
