/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard.Patient;

import Business.Model.Patient;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Shreya
 */
public class PatientWalletBalanceJPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form PatientWalletBalanceJPanelUI
     */
    Patient patient;
    JPanel workArea;
    public PatientWalletBalanceJPanelUI(Patient p,JPanel workArea) {
        initComponents();
        this.patient = p;
        this.workArea = workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        txtPatientInsuranceCover = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAddMoney = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtViewBalance = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCreditCard = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 214, 228, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Remaining Insurance Cover:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 468, -1, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 248, 228, -1));

        txtPatientInsuranceCover.setEnabled(false);
        add(txtPatientInsuranceCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 465, 224, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Expiry Date:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 217, 102, -1));

        jLabel12.setText("$");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 428, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("CVV");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 251, 97, -1));

        jLabel13.setText("$");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 468, -1, -1));

        btnAddMoney.setBackground(new java.awt.Color(0, 0, 0));
        btnAddMoney.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMoney.setText("Add Money to Wallet");
        btnAddMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMoneyActionPerformed(evt);
            }
        });
        add(btnAddMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 351, 167, 34));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Your Account Balace:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 428, -1, -1));

        txtViewBalance.setEnabled(false);
        txtViewBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewBalanceActionPerformed(evt);
            }
        });
        add(txtViewBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 425, 227, -1));

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 288, 228, -1));

        jLabel7.setText("$");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 291, -1, -1));
        add(txtCreditCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 228, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Amount:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 291, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Credit/Debit Card:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 183, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Wallet Balance");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 38, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/Patient/bg2 small.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnAddMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoneyActionPerformed
        patient.setAccountBal(patient.getAccountBal()+Integer.parseInt(txtAmount.getText()));
        txtViewBalance.setText(String.valueOf(patient.getAccountBal()));
    }//GEN-LAST:event_btnAddMoneyActionPerformed

    private void txtViewBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewBalanceActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) workArea.getLayout();
        workArea.remove(this);
        cardLayout.previous(workArea);    
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMoney;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCreditCard;
    private javax.swing.JTextField txtPatientInsuranceCover;
    private javax.swing.JTextField txtViewBalance;
    // End of variables declaration//GEN-END:variables
}
