/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard;

import Business.Ecosystem;
import Business.Model.Doctor;
import Business.Model.Hospital;
import Business.Model.Patient;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shreya
 */
public class GovernmentDashboardUI extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentDashboardUI
     */
    Ecosystem ecosystem;
    public GovernmentDashboardUI(Ecosystem e) {
        initComponents();
        this.ecosystem = e;
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNumberOfPatients = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGovPatient = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtNumberOfHospitals = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumberOfDoctors = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGovHospital = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGovDoctor = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. of Active Patients :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 127, -1));
        jPanel1.add(txtNumberOfPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 239, -1));

        tblGovPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient Name", "Patient Address", "Patient City"
            }
        ));
        jScrollPane1.setViewportView(tblGovPatient);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 679, 188));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No. of Hospitals :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));
        jPanel1.add(txtNumberOfHospitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 239, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. of  Active Doctors :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));
        jPanel1.add(txtNumberOfDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 239, -1));

        tblGovHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Hospital Name", "City"
            }
        ));
        jScrollPane2.setViewportView(tblGovHospital);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 679, 169));

        tblGovDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doctor Name", "Hospital Name", "No.of patients"
            }
        ));
        jScrollPane3.setViewportView(tblGovDoctor);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 733, 180));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Government");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/bg1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 790));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 800, 800));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblGovDoctor;
    private javax.swing.JTable tblGovHospital;
    private javax.swing.JTable tblGovPatient;
    private javax.swing.JTextField txtNumberOfDoctors;
    private javax.swing.JTextField txtNumberOfHospitals;
    private javax.swing.JTextField txtNumberOfPatients;
    // End of variables declaration//GEN-END:variables
    private void populateFields() {

        int patients = ecosystem.getPatientList().getPatientList().size();
        int hospitals = ecosystem.getHospitalList().getHospitalList().size();
        int doctors = ecosystem.getDoctorList().getDoctorList().size();
        
        
        txtNumberOfDoctors.setText(String.valueOf(doctors));
        txtNumberOfPatients.setText(String.valueOf(patients));
        txtNumberOfHospitals.setText(String.valueOf(hospitals));
        
        
        
        DefaultTableModel model = (DefaultTableModel) tblGovPatient.getModel();         
        model.setRowCount(0);
        
        for(Patient p : ecosystem.getPatientList().getPatientList())
        {
           
        
                        Object[] row = new Object[4];
                        row[0]=p;
                        row[1]=p.getAddress();
                        row[2]=p.getCity().getCityName();
                        
            

                        model.addRow(row);
  
            
        }
        
        
        DefaultTableModel model2 = (DefaultTableModel) tblGovHospital.getModel();         
        model2.setRowCount(0);
        
        for(Hospital h : ecosystem.getHospitalList().getHospitalList())
        {
           
        
                        Object[] row = new Object[2];
                        row[0]=h;
                        row[1]=h.getCity().getCityName();
                        
                        
            

                        model2.addRow(row);
  
            
        }
        
        
        DefaultTableModel model3 = (DefaultTableModel) tblGovDoctor.getModel();         
        model3.setRowCount(0);
        
        for(Doctor d : ecosystem.getDoctorList().getDoctorList())
        {
           
        
                        Object[] row = new Object[3];
                        row[0]=d;
                        row[1]=d.getHospital().getHospitalName();
                        row[2]=d.getDocPatList().size();
                        
                        
            

                        model3.addRow(row);
  
            
        }



    }
}
