/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard;

import Business.Admins.LaboratoryAdmin;
import Business.Ecosystem;
import Business.Model.Encounter;
import Business.Model.Patient;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shreya
 */
public class LabAdminDashboardUI extends javax.swing.JPanel {

    /**
     * Creates new form LabAdminDashboardUI
     */
    Ecosystem ecosystem;
    LaboratoryAdmin laboratoryAdmin;
   
    public LabAdminDashboardUI(Ecosystem ecosystem,LaboratoryAdmin laboratoryAdmin ) {
        initComponents();
        this.ecosystem=ecosystem;
        this.laboratoryAdmin=laboratoryAdmin;
        populateLabAdminPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLabTestList = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtLabAdminAmountToPay = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Admin");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLabTestList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient Name", "Treatment type", "Treatment status", "Encounter Name"
            }
        ));
        jScrollPane1.setViewportView(tblLabTestList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 101, 690, 188));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Mark Completed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 334, 175, 38));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Amount to be paid :");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 329, 229, 48));

        txtLabAdminAmountToPay.setEnabled(false);
        jPanel1.add(txtLabAdminAmountToPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 329, 275, 48));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Lab Admin");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/bg1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int selectedRowIndex = tblLabTestList.getSelectedRow();

        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row of Encounter table");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblLabTestList.getModel();
        Encounter e = (Encounter) model.getValueAt(selectedRowIndex, 3);

        Patient p = (Patient) model.getValueAt(selectedRowIndex, 0);

        System.out.println("Hello" + p.getName());

        if(p.getInsuranceRequest().equals("Approved") && (p.getCoverAmount()>= Integer.parseInt(txtLabAdminAmountToPay.getText())))
        {
            if(p.getCoverAmount()>= Integer.parseInt(txtLabAdminAmountToPay.getText()))
            {

                if(e.getTreatment().getLaboratoryStatus().equalsIgnoreCase("Pending"))
                {
                    p.setCoverAmount(p.getCoverAmount()- Integer.parseInt(txtLabAdminAmountToPay.getText()));
                    e.getTreatment().setLaboratoryStatus("Completed");
                    JOptionPane.showMessageDialog(this, "Laboratory Request is Completed");

                }

                else{

                    JOptionPane.showMessageDialog(this, "Laboratory Request is Already Complete");

                }

            }

        }

        else if((p.getAccountBal() >= Integer.parseInt(txtLabAdminAmountToPay.getText())))
        {
            if(e.getTreatment().getLaboratoryStatus().equalsIgnoreCase("Pending"))
            {
                p.setAccountBal(p.getAccountBal()- Integer.parseInt(txtLabAdminAmountToPay.getText()));
                e.getTreatment().setLaboratoryStatus("Completed");
                JOptionPane.showMessageDialog(this, "Laboratory Request is  Completed");

            }

            else{

                JOptionPane.showMessageDialog(this, "Laboratory Request is Already Completed");

            }

        }

        else {
            JOptionPane.showMessageDialog(this, "Patient doesn't have enough balance in account.");

        }

        populateLabAdminPanel();
        txtLabAdminAmountToPay.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRowIndex = tblLabTestList.getSelectedRow();

        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row of Encounter table");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblLabTestList.getModel();
        Encounter e = (Encounter) model.getValueAt(selectedRowIndex, 3);

        if(e.getTreatment().getLaboratoryList().get(0).getLabTest().equals("Chemo Theorapy"))
        {
            txtLabAdminAmountToPay.setText("2000");
        }

        if(e.getTreatment().getLaboratoryList().get(0).getLabTest().equals("Radiation Theoray"))
        {
            txtLabAdminAmountToPay.setText("3000");
        }

        if(e.getTreatment().getLaboratoryList().get(0).getLabTest().equals("Surgery"))
        {
            txtLabAdminAmountToPay.setText("4000");
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLabTestList;
    private javax.swing.JTextField txtLabAdminAmountToPay;
    // End of variables declaration//GEN-END:variables

    private void populateLabAdminPanel() {
            DefaultTableModel model = (DefaultTableModel) tblLabTestList.getModel();         
         model.setRowCount(0);
        
        for(Patient p : ecosystem.getPatientList().getPatientList())
        {
           for(Encounter e : p.getEncounterHistory())
           {
                        Object[] row = new Object[4];
                        row[0]=p;
                        row[1]=e.getTreatment().getLaboratoryList().get(0).getLabTest();
                        row[2]=e.getTreatment().getLaboratoryStatus();
                        row[3]=e;
                     model.addRow(row);
       
           }
            
        }
    }
}
