/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard;

import Business.Admins.NGOAdmin;
import Business.Ecosystem;
import Business.Model.Encounter;
import Business.Model.Patient;
import Business.sendMail;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shreya
 */
public class NGOAdminDashboardUI extends javax.swing.JPanel {

    /**
     * Creates new form NGOAdminDashboardUI
     */
    Ecosystem ecosystem;
    NGOAdmin nGOAdmin;
    Patient selectedPatient;
    public NGOAdminDashboardUI(Ecosystem e,NGOAdmin na) {
        initComponents();
        this.ecosystem = e;
        this.nGOAdmin = na;
        populateNGOPatientTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNGOAdminPatient = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNGOAdminPatientEncounter = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNGOAdminPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient Name", "City", "Account Balance"
            }
        ));
        jScrollPane1.setViewportView(tblNGOAdminPatient);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 84, 683, 209));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Medical Bills");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 201, -1));

        tblNGOAdminPatientEncounter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Encounter", "Diagnosis", "Treatment Status", "Medical Status"
            }
        ));
        jScrollPane2.setViewportView(tblNGOAdminPatientEncounter);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 367, 683, 193));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sponsor Medical Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 198, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("NGO Admin");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/bg1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        populateNGODashboardTable();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int selectedRowIndex = tblNGOAdminPatientEncounter.getSelectedRow();

        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row of Encounter table");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNGOAdminPatientEncounter.getModel();
        Encounter e = (Encounter) model.getValueAt(selectedRowIndex, 0);

        if(!e.getTreatment().getMedicineStatus().equalsIgnoreCase("Completed"))
        {
            e.getTreatment().setMedicineStatus("Completed");
            try{
                sendMail.send(selectedPatient.getEmail(), "Your NGO sponsorship results are here !!!!!", "Congratulations you have been sponsored by the NGO : "+nGOAdmin.getName() + "\n The status of the same has been reflected in the table");
            }
            catch(Exception exp){
                
            }
            JOptionPane.showMessageDialog(this, "You have sponsored the selected patient");

            populateNGODashboardTable();

        }

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblNGOAdminPatient;
    private javax.swing.JTable tblNGOAdminPatientEncounter;
    // End of variables declaration//GEN-END:variables

    private void populateNGODashboardTable() {
       int selectedRowIndex = tblNGOAdminPatient.getSelectedRow();
        
        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row of Encounter table");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNGOAdminPatient.getModel();
        Patient  p = (Patient) model.getValueAt(selectedRowIndex, 0);
        selectedPatient = p;
        
        DefaultTableModel model1 = (DefaultTableModel) tblNGOAdminPatientEncounter.getModel();
        model1.setRowCount(0);
        
        
       for( Encounter e : p.getEncounterHistory())
       {
            Object[] row = new Object[4];
            row[0]=e;
            row[1]=e.getDiagnosis();
            row[2]=e.getTreatment().getTreatmentStatus();
            row[3]=e.getTreatment().getMedicineStatus();
            model1.addRow(row);   
       }
    }

    private void populateNGOPatientTable() {
        DefaultTableModel model = (DefaultTableModel) tblNGOAdminPatient.getModel();   
         model.setRowCount(0);
        for(Patient p: ecosystem.getPatientList().getPatientList())
        {
            if(p.isNgoRequest())
            {
                        Object[] row = new Object[3];
                        row[0]=p;
                        row[1]=p.getCity().getCityName();
                        row[2]=p.getAccountBal();
                        model.addRow(row);
                
            }   
        }
    }
}
