/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard;

import Business.Admins.PharmacyAdmin;
import Business.Ecosystem;
import Business.Model.Encounter;
import Business.Model.Medicine;
import Business.Model.Patient;
import Business.Model.Treatment;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shreya
 */
public class PharmacyDashboardUI extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyDashboardUI
     */
    Ecosystem ecosystem;
    PharmacyAdmin pharmacyAdmin;
    public PharmacyDashboardUI(Ecosystem e,PharmacyAdmin pa) {
        initComponents();
        this.ecosystem = e;
        this.pharmacyAdmin = pa;
        populatePharmacyDashboardTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPharAdminPatient = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPharPatMedicineList = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAmountTobePaid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPharAdminPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Patient Name", "Request Status"
            }
        ));
        jScrollPane1.setViewportView(tblPharAdminPatient);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 111, 733, 132));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Medicine List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 202, 33));

        tblPharPatMedicineList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Medicine", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(tblPharPatMedicineList);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 438, 578, 147));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Mark Complete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 280, 187, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Amount to be paid:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 381, -1, -1));

        txtAmountTobePaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountTobePaidActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmountTobePaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 378, 144, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pharmacy");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/bg1.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int selectedRowIndex = tblPharAdminPatient.getSelectedRow();

        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row of Encounter table");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblPharAdminPatient.getModel();
        Treatment t = (Treatment) model.getValueAt(selectedRowIndex, 1);

        //       ----------------------------------------------------------------------------------

        DefaultTableModel model1 = (DefaultTableModel) tblPharPatMedicineList.getModel();
        model1.setRowCount(0);

        int amountToPay = 0;

        for(Medicine m : t.getMedicineList() )
        {

            amountToPay+=10*m.getQuantity();

            Object[] row1 = new Object[3];
            row1[0]=m.getMedicine();
            row1[1]=m.getQuantity();

            model1.addRow(row1);

        }

        txtAmountTobePaid.setText(String.valueOf(amountToPay));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int selectedRowIndex = tblPharAdminPatient.getSelectedRow();

        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a row of Encounter table");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblPharAdminPatient.getModel();
        Treatment t = (Treatment) model.getValueAt(selectedRowIndex, 1);
        Patient p = (Patient) model.getValueAt(selectedRowIndex, 0);

        if(p.getInsuranceRequest().equals("Approved") && (p.getCoverAmount()>= Integer.parseInt(txtAmountTobePaid.getText())))
        {
            if(p.getCoverAmount()>= Integer.parseInt(txtAmountTobePaid.getText()))
            {

                if(t.getMedicineStatus().equals("Pending"))
                {
                    p.setCoverAmount(p.getCoverAmount()- Integer.parseInt(txtAmountTobePaid.getText()));
                    t.setMedicineStatus("Completed");
                    JOptionPane.showMessageDialog(this, "Medicine Request is Completed");

                }

                else{

                    JOptionPane.showMessageDialog(this, "Medicine Request is Already Complete");

                }

            }

        }

        else if((p.getAccountBal() >= Integer.parseInt(txtAmountTobePaid.getText())))
        {
            if(t.getMedicineStatus().equals("Pending"))
            {
                p.setAccountBal(p.getAccountBal()- Integer.parseInt(txtAmountTobePaid.getText()));
                t.setMedicineStatus("Completed");
                JOptionPane.showMessageDialog(this, "Medicine Request is Completed");

            }

            else{

                JOptionPane.showMessageDialog(this, "Medicine Request is Already Complete");

            }

        }

        else {
            JOptionPane.showMessageDialog(this, "Patient doesn't have enough balance in account.");

        }

        populatePharmacyDashboardTable();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAmountTobePaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountTobePaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountTobePaidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPharAdminPatient;
    private javax.swing.JTable tblPharPatMedicineList;
    private javax.swing.JTextField txtAmountTobePaid;
    // End of variables declaration//GEN-END:variables

    private void populatePharmacyDashboardTable() {
      DefaultTableModel model = (DefaultTableModel) tblPharAdminPatient.getModel();
               
                  
                model.setRowCount(0);
        
        for(Patient p : ecosystem.getPatientList().getPatientList())
        {
           for(Encounter e : p.getEncounterHistory())
           {
                Object[] row = new Object[2];
                row[0]=p;
                row[1]=e.getTreatment();
                model.addRow(row);
           }
            
        }
    }
}
